### ISSUE TITLE
Issues while running cp-vault-pki/prep 

### ISSUE THREAD

**Issue by arpan57** [jeqo/docker-composes#1]
Hi, 
 First of all very good work on putting things together. I was trying to implement CRL checking on Strimzi and while good search I fell on this repo. 
As per the README I am trying to run 
`$ make prep 
` but it fails to start with tho issues. 

One is related to image version variable (CP_VERSION in the docker-compose manifest) - which I fixed by changing the version for confluent zookeeper/kafka images 
Post that it creates the vault secrets, PKI certificates etc. 
But it fails while it tries to create topics, it cannot find the /bin/kafka-topics.sh script. 

```
Creating cp-vault-pki_zookeeper_1 ... done
Creating cp-vault-pki_kafka_1     ... done
/bin/kafka-topics.sh --topic test --bootstrap-server localhost:9092 --create
make: /bin/kafka-topics.sh: No such file or directory
make: *** [kafka_topic] Error 1
make: /bin/kafka-topics.sh: No such file or directory
```

I didn't debug much but should be possible to point to the right script. Probably in my image version the path is changed. 
Do you remember which version of Confluent platform did you use for these scripts?  So, that I can set the value of CP_VERSION in docker compose accordingly and verify. 

Thanks, 
Arpan

**Comment by jeqo** [comment]
Hi there! Thanks for opening this issue.
At the moment the script is relying on env var $KAFKA_HOME to point to the Apache Kafka directory: 

https://github.com/jeqo/docker-composes/blob/7b51deca9c66ab963c8544c6596bcd78e148336c/cp-vault-pki/Makefile#L106

This should be available on your host to work properly. I worked with AK 3.0 and CP 7.0.
Hope this helps.

**Comment by jeqo** [comment]
Will close this one for the time being. Feel free to reopen if you still have issues running the demo.

Thanks!

**Comment by arpan57** [comment]
> Hi there! Thanks for opening this issue. At the moment the script is relying on env var $KAFKA_HOME to point to the Apache Kafka directory:
> 
> https://github.com/jeqo/docker-composes/blob/7b51deca9c66ab963c8544c6596bcd78e148336c/cp-vault-pki/Makefile#L106
> 
> This should be available on your host to work properly. I worked with AK 3.0 and CP 7.0. Hope this helps.



> Hi there! Thanks for opening this issue. At the moment the script is relying on env var $KAFKA_HOME to point to the Apache Kafka directory:
> 
> https://github.com/jeqo/docker-composes/blob/7b51deca9c66ab963c8544c6596bcd78e148336c/cp-vault-pki/Makefile#L106
> 
> This should be available on your host to work properly. I worked with AK 3.0 and CP 7.0. Hope this helps.

Thanks, I will give it a go.

**Comment by arpan57** [comment]
> Hi there! Thanks for opening this issue. At the moment the script is relying on env var $KAFKA_HOME to point to the Apache Kafka directory:
> 
> https://github.com/jeqo/docker-composes/blob/7b51deca9c66ab963c8544c6596bcd78e148336c/cp-vault-pki/Makefile#L106
> 
> This should be available on your host to work properly. I worked with AK 3.0 and CP 7.0. Hope this helps.

Thanks I will git it go.
